package com.example.gbuddy.models.constants;

public enum MatchRequestConstants {
    REQUESTED("REQUESTED"),
    REQUEST_ALREADY_EXISTS("REQUEST_ALREADY_EXISTS[ID:%s]"),
    NO_REQUEST_IS_PRESENT("NO_REQUEST_IS_PRESENT[ID:%s]"),
    NO_REQUESTS_PRESENT("NO_NEW_FRIEND_REQUESTS[ID:%s]"),
    FRIEND_REQUESTS_PRESENT("FRIEND_REQUESTS_PRESENT"),
    FAILED_TO_FIND_FRIEND_REQUEST("FAILED_TO_FIND_FRIEND_REQUEST"),
    NO_LOOKUP_PRESENT("NO_LOOKUP_PRESENT_SKIPPING_RECORD[ID:%s]"),
    NO_BRANCH_PRESENT("NO_BRANCH_PRESENT_SKIPPING_RECORD[GYM:%s, BRANCH:%s]"),
    NO_USER_PRESENT("NO_USER_PRESENT_SKIPPING_RECORD[ID:%s]"),
    REQUEST_IS_ACCEPTED("REQUEST_IS_ALREADY_ACCEPTED[ID:%s]"),
    UNABLE_TO_ADD_TO_BUDDY_GRAPH("UNABLE_TO_ADD_TO_BUDDY_GRAPH"),
    MATCH_REQUEST_STATUS_NOT_ACCEPTED("MATCH_REQUEST_STATUS_NOT_ACCEPTED[ID:%s,STATUS:%s]"),
    NO_MATCH_REQUEST_PRESENT("NO_MATCH_REQUEST_PRESENT[ID:%s]"),
    NO_MATCH_LOOKUP_RECORD("NO_MATCH_LOOKUP_RECORD[ID:%s]"),
    ACCEPTED("ACCEPTED"),
    REJECTED("REJECTED");

    private String status;

    MatchRequestConstants(String status) {
        this.status = status;
    }

    public String getStatus() {
        return status;
    }
}
